project:
  title: "ediSurveys"
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - codebook.qmd
  
website:
  title: "EDI survey"
  site-url: https://psychopy.github.io/psychopy-edi-survey/
  navbar:
    background: "#26DCF0"
    search: true
    left:
      - text: "Main report"
        file: index.html
      - text: "Codebook"
        file: codebook.html