---
title: "Codebook"
subtitle: "Equity, diversity, and inclusion in the PsychoPy community"
ndate: now
date-format: "D MMM YYYY, h:mm a"
bibliography: bibs/grateful-refs-codebook.bib
---

```{r}
#| label: getAndAttachPackages
#| include: false

# list the required packages

packagesRequired <- c(
  "codebook", 
  "grateful", 
  "knitr",
  "showtext",
  "sysfonts"
  )


# Uncomment the code below to install any packages you're missing from the 
# list in packagesRequired

# packagesInstalled <- installed.packages()[,"Package"]
# packagesMissing <- packagesRequired[!(packagesRequired %in% packagesInstalled)]
# if(length(packagesMissing)) install.packages(packagesMissing, repos = getCRANmirrors()[1,"URL"])

# attach the packages
invisible(lapply(packagesRequired, require, character.only=T))

```

```{r}
#| label: getFontRaleway 
#| output: false
## use *raleway* font throughout
## an active internet connection is required for this step

font_add_google("Raleway", "raleway")
showtext_auto()

```

```{r}
#| label: readTidiedLabeledData
#| include: false

data <- readRDS("data/tidyLabeledSurveyData.rds")
              
```

# Table

::: {.callout-warning}
The `.pdf` download does not work properly. For a good `.pdf`, please choose `Print` then adjust the settings to print to pdf.
:::

```{r}
#| label: retrieveCodebookItems

codebook_items(data)

```

# Main *R* packages used

```{r}
#| label: citePackages
#| results: asis

    pkgs <- cite_packages(
      pkgs = packagesRequired,
      output = "table", 
      out.dir = getwd(),
      citation.style = apa.csl,
      cite.tidyverse = F,
      bib.file = "bibs/grateful-refs-codebook.bib"
      )
    knitr::kable(pkgs)

```
